### ISSUE TITLE
buggy url resolve

### ISSUE THREAD

**Issue by deodeveloper** [antivanov/js-crawler#1]
buggy url resolve

Solution: 
at line 3: var url = require('url'); 
at line 61:  link = url.resolve(baseUrl, link);

I couldn't able to commit the change due to permission issue. You could update.

Explanation:

 Example if baseUrl is http://www.syr.edu/facultyandstaff/index.html and
anchor url is ../admissions/index.html, then it was trying to fetch
http://www.syr.edu/facultyandstaff/index.html../admissions/index.html
which is wrong.

Fixed with node builtin function url.resolve(from, to), Ref:
https://nodejs.org/docs/latest/api/url.html

**Comment by antivanov** [comment]
Hi, thank you for reporting the issue. You can also create a pull request which I will then merge https://help.github.com/articles/using-pull-requests/ "Fork & pull" , or I will commit the change myself.

**Comment by deodeveloper** [comment]
Thank. Will do a pull request and will make changes.

**Comment by antivanov** [comment]
Thanks for the contribution, merged.
