### ISSUE TITLE
How do you slow this down so it's not hammering the server you are crawling?

### ISSUE THREAD

**Issue by Jakobud** [antivanov/js-crawler#10]
Some kind of delay or setTimeout or something? Can you do it with this?

**Comment by antivanov** [comment]
We may need some sort of throttling support, like no more than 1 request for 5 seconds, then we can expose an additional option that would control the throttling behavior. I will take a look how this can be done and whether there are other ways to solve this problem.

**Comment by antivanov** [comment]
A new option `maxRequestsPerSecond` has been added. For example, to limit the rate of HTTP requests to maximum 1 per 5 seconds you can configure the crawler like this:

```javascript
var Crawler = require("js-crawler");

var crawler = new Crawler().configure({maxRequestsPerSecond: 0.2});

crawler.crawl({
  url: "https://github.com",
  success: function(page) {
    console.log(page.url);
  },
  failure: function(page) {
    console.log(page.status);
  }
});
```

**Comment by antivanov** [comment]
Please, let me know if the solution works for you, and, please, re-open the issue if the original problem has not been solved.
