### ISSUE TITLE
How can we crawl local websites?

### ISSUE THREAD

**Issue by Redsandro** [antivanov/js-crawler#12]
Trying to crawl a local project.

`[Error: Invalid URI "./test/index.html"]`

`[Error: Invalid URI "/var/www/sites/test/index.html"]`

`[Error: Invalid URI "file:///var/www/sites/test/index.html"]`

**Comment by antivanov** [comment]
Sorry, for a small delay with the response, somehow I missed this issue. 

The crawler works through the HTTP/HTTPS protocols, in case resources are hosted locally and are not exposed via these protocols they will not be crawled.

A simple solution in this case may be to serve the local files with an HTTP server.

Maybe we also need to think how to handle such errors better and provide more meaningful error messages, i.e. just print a warning that some url will not be crawled.

**Comment by Redsandro** [comment]
Ah, of course, I don't know why I didn't try that one myself.

> A simple solution in this case may be to serve the local files with an HTTP server.

Thanks. :smile:
