### ISSUE TITLE
The "depth" for crawling a website completely

### ISSUE THREAD

**Issue by rahul-desai3** [antivanov/js-crawler#13]
I see that setting the `depth` value gets you to crawl the website to that particular level.

I am wondering how to configure the crawler so as to crawl the website completely without having it to go to other domain. For example - If I want to crawl `https://www.someDomain.com`, I want it to return all URLs in this website like `https://www.someDomain.com/something`, `https://www.someDomain.com/somethingMore/abc`, and so on. If `https://www.someDomain.com/something` has an external link like `https://www.externalDomain.com/`, it shouldnt go ahead with that.

Ultimately, I am looking to find all the email addresses in a given website. So far, I know that the node.js module `node-scrapy` can help me find email addresses for a particular URL/webpage.

Thanks,
Rahul

**Comment by antivanov** [comment]
Hi Rahul,

One way to do this can be to set a maximum depth to sufficiently large number, even Number.POSITIVE_INFINITY and define a filter for the urls that should be visited.

It should look something like this:

```javascript
var Crawler = require("js-crawler");

var crawler = new Crawler().configure({
  depth: Number.POSITIVE_INFINITY,
  shouldCrawl: function(url) {
    return url.indexOf("someDomain.com") >= 0;
  }
});

crawler.crawl({
  url: "http://www.someDomain.com",
  success: function(page) {
    //...Find something on a page
  },
  failure: function(page) {
    console.log("Could not load page. URL = " +  page.url + " error = " + page.error);
  },
  finished: function(crawledUrls) {
    //...Handle the collected results
  }
});

```

**Comment by rahul-desai3** [comment]
@antivanov That seems like a good idea. Is there any way to wait for the `onload` event?

**Comment by antivanov** [comment]
> Is there any way to wait for the onload event?
The crawler intentionally treats page content as text and does not evaluate any JavaScript, i.e. it is not a browser, and does not handle the 'onload' event. Other crawlers may evaluate the page and render the HTML. You may want to consider those instead if you need to parse the page content.

**Comment by rahul-desai3** [comment]
Gotcha.
