### ISSUE TITLE
Ajax crawling

### ISSUE THREAD

**Issue by edouardkombo** [antivanov/js-crawler#16]
I'm trying to crawl a page which have some content loaded in javascript after a certain time.

Is there a way to pause the script in order to wait for the ajax content?

**Comment by antivanov** [comment]
The crawler does not interpret JavaScript and treats the page as text content. You may want to look at other crawlers that have browser functionality, like http://docs.casperjs.org/en/latest/

**Comment by antivanov** [comment]
Actually I am thinking of making the crawler more flexible and allowing it to use, for example PhantomJS and making the choice of the underlying browsing mechanism transparent. But this will take some time and will be done only in more distant future.
