### ISSUE TITLE
When run asynchronous by Executor, depth lost its scope

### ISSUE THREAD

**Issue by tibetty** [antivanov/js-crawler#23]
Yesterday I tried to crawl a simple 3-layer-structured website (http://transit.yahoo.co.jp/station/top), and found that it had never reached the 3rd layer.  When looked inside into _js-crawler_ to figure out what happened by instrumenting "console.log" in btwn _crawlUrl_ method, I found that  depth become "_undefined_" except for requesting the very first page.  It should be a scope related issue but I have not come out a solution to fix yet.  I posted this issue here for @antivanov 's consideration.

**Comment by antivanov** [comment]
Thank you, I will take a look. Also I may have an idea how to automate testing for the scenario you are describing or similar ones.

**Comment by tibetty** [comment]
@antivanov , I spent almost 2 days trying to address this issue, and FINALLY, EVENTUALLY, AT LAST I had the root-cause located - phew! it's a very very very tiny but disastrous bug.  Will request a pull to upload my revision, and I bet you will LYAO as well, :8ball:

**Comment by antivanov** [comment]
Merged the pull request, thank you for fixing this issue, nice job :+1:
