### ISSUE TITLE
Publishing latest fixes?

### ISSUE THREAD

**Issue by mledwards** [antivanov/js-crawler#28]
Hello, it looks like your recent fixes have fixed an issue I was having when the content-type was undefined. Will you be publishing this to npm anytime soon?

Thanks for a great package!

**Comment by antivanov** [comment]
Hi, yes, I am trying to keep the package in NPM up to date, the latest one is 0.3.11, I plan to write a few more test cases and will publish the newer version in the next few days.

Thanks!

**Comment by antivanov** [comment]
Published the version 0.3.13

**Comment by mledwards** [comment]
Thanks!
