### ISSUE TITLE
Is it can use by only JavaScript?

### ISSUE THREAD

**Issue by mqliutie** [antivanov/js-crawler#29]
I mean it is possible for frontend to use it?

**Comment by antivanov** [comment]
The expected way to run the crawler is to run it with Node.js

This limitation is there because it depends on the 'request' NPM package. You may try to use browserify to get a browser version of 'js-crawler' but I have not tried to do it myself.

What is the exact scenario in which you would like to crawl the web pages from a browser instance? Maybe there are some alternative solutions rather than to try to make js-crawler work in a browser environment.

**Comment by mqliutie** [comment]
I just want to get some website HTML content. I have tried to use iFrame to load or jQuery to load some page. But I can not get it.Because `cross-domain`.So I want to crawler these content

**Comment by tibetty** [comment]
I believe so if browserify it although it's not tested.  BTW, why not to use AJAX (XMLHTTPRequest) mechanism built-in browser to do so on front-end?

**Comment by mqliutie** [comment]
I have tested through browserify.


**index.js**
```js
var Crawler = require("js-crawler");

new Crawler().configure({depth: 3})
    .crawl("http://www.google.com", function onSuccess(page) {
        console.log(page.url);
    });
```

Run `browserify ./index.js > index.js`

There is an error :
`etch API cannot load https://www.google.com/. Redirect from 'https://www.google.com/' to 'https://www.google.com.hk/?gfe_rd=cr&ei=UgAgWOKuGMzU8Af315CQDA' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

If use AJAX of jQuery there also an error :
`XMLHttpRequest cannot load https://www.google.com.hk/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:63342' is therefore not allowed access.`

This is why I want to **crawler** some HTML content

**Comment by tibetty** [comment]
You want to crawl google service? You need some tricks...  First of all,
you need to specify an browser-like agent in your headers and maybe more.
A practical way is to mimic requests from a browser, in particular,
Chrome.  To learn what exactly happens, enter the "Developer Tools" and
capture network communication, and then you will figure it out easily.
Good luck!

**Comment by antivanov** [comment]
Cross-origin requests are not allowed in a browser by default this is why there is a message about no 'Access-Control-Allow-Origin' header missing https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

> For security reasons, browsers restrict cross-origin HTTP requests initiated from within scripts. For example, XMLHttpRequest and Fetch follow the same-origin policy.

If we want to request a document from another domain and have no control over the HTTP headers returned by the server for the document then we would get such an error.

Then the only alternative seems to be to use the crawler from a Node environment where there are no such restrictions as in a browser.
