### ISSUE TITLE
Add <base> tag support for relative urls

### ISSUE THREAD

**Issue by sedran** [antivanov/js-crawler#32]
Some pages use HTML <base> tag in their <head> tag. In this case, relative urls should be processed according to the base url. 

For instance, 
- I go to the page http://www.milliyet.com.tr/astroloji/
- It has this base: <base href="http://www.milliyet.com.tr/"/>
- It contains an anchor with a relative url: <a href="yengec" target="_blank">Yengec</a>
- When I click that anchor, the browser goes to http://www.milliyet.com.tr/yengec
- When js-crawler sees that link, it goes to http://www.milliyet.com.tr/astroloji/yengec , which is 404.

See also: http://www.w3schools.com/tags/tag_base.asp

**Comment by antivanov** [comment]
The support for the base tag should be added, thank you for filing the issue, I will take a look and release an updated when it is fixed.

**Comment by antivanov** [comment]
The fix has been published in the version 0.3.13, please, check if it now works in the original use case. If problems still remain with the base tag handling, please, re-open the issue.

Added a few unit tests and end-to-end tests that verify the handling of the base url.
