### ISSUE TITLE
Page that linked to current page

### ISSUE THREAD

**Issue by jankcat** [antivanov/js-crawler#35]
Hello,

Is it possible to find what page linked to the current page in a callback? 

Example use case, I am crawling all the links on my site for 404 errors. I can currently use the failure callback to retrieve the error, but a useful piece of information would be understanding what pages linked to that page (how the crawler 'got to that page' from my site). That way I can remedy the situation by fixing the dead link on the link-out page.

Does this feature exist currently?

**Comment by jankcat** [comment]
Note, I added this feature in https://github.com/antivanov/js-crawler/pull/36

**Comment by antivanov** [comment]
Thanks, seems like a nice feature to add, I will take a look at the merge request.

**Comment by jankcat** [comment]
Closing as PR merged :)

**Comment by antivanov** [comment]
The 'referer' field feature has been published in the release 0.3.16 https://www.npmjs.com/package/js-crawler

I also added the documentation and updated a couple of unit tests that were broken after the merge.

Thank you for the contribution
