### ISSUE TITLE
Basics

### ISSUE THREAD

**Issue by peterweter1** [antivanov/js-crawler#46]
Hi,

Sorry for this noob question but I've lost quite some time trying to get this to work. 
I'm completely new to grunt, karma etc. but I know my way in Javascript.

I try to get this to run but I don't know where to put my file in order for it to run.
I've installed everything needed:

Package.json
```
{
  "name": "crawler",
  "version": "0.3.18",
  "description": "Web crawler for Node.js",
  "main": "crawler.js",
  "directories": {
    "example": "examples"
  },
  "dependencies": {
    "request": "~2.55.0",
    "underscore": "~1.8.3"
  },
  "devDependencies": {
    "browserify": "^13.0.0",
    "grunt": "^0.4.5",
    "grunt-eslint": "^18.0.0",
    "grunt-karma": "^0.12.2",
    "jasmine-core": "^2.4.1",
    "js-crawler": "^0.3.18",
    "karma": "^0.13.22",
    "karma-browserify": "^5.0.2",
    "karma-chrome-launcher": "^0.2.2",
    "karma-firefox-launcher": "^0.1.7",
    "karma-jasmine": "^0.3.8",
    "karma-jasmine-html-reporter": "^0.2.0",
    "karma-phantomjs-launcher": "^1.0.0",
    "phantomjs-prebuilt": "^2.1.6",
    "watchify": "^3.7.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/antivanov/js-crawler"
  },
  "keywords": [
    "web-crawler",
    "crawler",
    "scraping",
    "website-crawler",
    "crawling",
    "web-bot"
  ],
  "author": "Anton Ivanov, anton.al.ivanov@gmail.com",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/antivanov/js-crawler/issues"
  },
  "homepage": "https://github.com/antivanov/js-crawler"
}
```

Gruntfile:

```
require('grunt-karma');

module.exports = function(grunt) {

  grunt.initConfig({
    eslint: {
      target: ['Gruntfile.js', 'crawler.js', 'spec/**/*.js']
    },
    karma: {
      options: {
        frameworks: ['jasmine', 'browserify'],
        files: ['crawler.js', 'spec/*.spec.js'],
        browsers: ['PhantomJS'],
        singleRun: true,
        preprocessors: {
          'crawler.js': ['browserify'],
          'spec/**/*.js': ['browserify']
        },
        browserify: {
          debug: true
        }
      },
      unit: {
        files:
          {
            src: ['spec/**/*.js']
          }
      },
      unit_browser: {
        browsers: ['Firefox'],
        reporters: ['kjhtml'],
        singleRun: false,
      }
    }
  });

  grunt.loadNpmTasks('grunt-eslint');
  grunt.loadNpmTasks('grunt-karma');

  grunt.registerTask('default', ['eslint', 'karma:unit']);
};
```

My own created file:

```
var Crawler = require("js-crawler");
var url = "https://github.com";

var cra = new Crawler().configure({
    // maxRequestsPerSecond: 1,
    // maxConcurrentRequests: 5,
    // ignoreRelative: true,
    // depth: 1,
});

cra.crawl({
    url: url,
    success: function(page) {
        console.log(page.url);
    },
    failure: function(page) {
        console.log(page.status);
    },
    finished: function (crawledUrls) {
        console.log(crawledUrls);
    }
}, function(response) {
    console.log("ERROR occurred:");
    console.log(response.status);
    console.log(response.url);
    console.log(response.referer);
});
```

I've used the commands `grunt karma:unit` & `grunt karma:unit_browser` in my 'gruntfile.js' folder.
I've placed my own file in the same directory as gruntfile.js.
I also tried placing it in spec/.
Both commands give no errors and run but I'm not getting any output? When the browser opens the browserconsole is empty, if I refresh the page it takes a bit to load bu the console remains empty. 

I know the solution is probably very simple but forgive me for being new to this and wanting to learn :).
I just want the output of the crawler displayed somewhere so I can start playing with it.

**Comment by antivanov** [comment]
Hi Peter,

Do you want to set up a development environment or just use the crawler for crawling?

1. If you want to set up a development environment (in order to make changes to the crawler)

- Check out the source code `git clone https://github.com/antivanov/js-crawler`
- Run `npm install` to install the dependencies

After that it should be possible to run `grunt karma:unit` and `grunt karma:unit_browser` and make changes to the source code of the crawler.

2. If you want to just use the crawler, then it can simply be installed with (globally with the -g option if you do not want to created a separate package)

`npm install -g js-crawler`

After that it should be possible to import the crawler and the following should work:

```javascript
var Crawler = require("js-crawler");
var url = "https://github.com";

var cra = new Crawler().configure({
    // maxRequestsPerSecond: 1,
    // maxConcurrentRequests: 5,
    // ignoreRelative: true,
    // depth: 1,
});

cra.crawl({
    url: url,
    success: function(page) {
        console.log(page.url);
    },
    failure: function(page) {
        console.log(page.status);
    },
    finished: function (crawledUrls) {
        console.log(crawledUrls);
    }
}, function(response) {
    console.log("ERROR occurred:");
    console.log(response.status);
    console.log(response.url);
    console.log(response.referer);
});
```

**Comment by peterweter1** [comment]
Thanks for your help. Got it to work now! Mixed up the 2 possibilities.

Last question, is it possible to interact with an external webpage? Like trigger a click?
I want to crawl a webpage which has a cookiewall. 
The button which needs to be clicked is an <input type=submit> element wrapped in a form.
Really curious if this is even possible or if you can think of another solution.

Once again, thanks!

**Comment by antivanov** [comment]
Unfortunately, in the current version it is not possible to interact with the page/execute JavaScript on the page. Now the crawler uses the `request` module that just returns the text content of the page.

In the future versions it should be possible to add support for alternative request mechanisms, maybe using something like PhantomJS which is more like a real browser. However, this is still only in the plans.
