### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by zaszlo** [antivanov/js-crawler#48]
Maybe I have problems with my npm, but I can't run js-crawler... in the usage only example configurations are given and usage of those js configurations with js-crawler is actually omitted. 

I have ran npm install js-crawler but I didn't get a js-crawler command to specify for it a js config file. Seems not to work out with npm run or serve...

I tried and downloaded the packaged via git and run npm install, and just get two warnings which I think is not a problem:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

I don't get it, how to started using js-crawler, please help.

**Comment by antivanov** [comment]
Hi,

Probably the documentation is a bit unclear about this and needs to be improved. The crawler scripts should be run with Node.js. For example, if there is a file angular_links_from_reddit.js in the current directory with the following contents:

```javascript
/*
 * Demonstrates how crawler results can be filtered.
 */
var Crawler = require("js-crawler");

new Crawler().configure({depth: 2}).crawl("http://www.reddit.com/r/javascript/", function onSuccess(page) {
  if (page.url.indexOf("angular") >= 0) {
    console.log(page.url);
  }
});
```

Then we can install the crawler globally `npm install js-crawler -g` and run it by typing the following command line:

```
node angular_links_from_reddit.js
```

**Comment by zaszlo** [comment]
Thanks, now it is clear.
