### ISSUE TITLE
Ability to pass custom user agents to crawler requests.

### ISSUE THREAD

**Issue by jexmex** [antivanov/js-crawler#5]
Most crawlers have the ability to send out a custom user agent, but there are not options currently to do that with this crawler.

I have created the code to do this, and a pull request will be coming.

**Comment by jexmex** [comment]
I actually am wondering if just being able to pass a request wrapper (see request.defaults() documentation) would be best. Doing it that way also opens up the option for more flexibility with the requests.

**Comment by antivanov** [comment]
Looks like a good enhancement, I will check out the PR.

**Comment by antivanov** [comment]
Tested on my machine. 

Like it was noted, request.defaults also provides a mechanism for setting the headers https://www.npmjs.com/package/request but I think we still need to provide a method to set headers: 

1. Setting headers via request.defaults can lead to default request headers might be a non-transparent side-effect of using the crawler
2. In this case it is better to have several ways to do the same thing, so a new option for the crawler to set use agent is welcome

I will merge the PR and update the NPM package, thank you for the nice contribution. Actually maybe we can also think about generalizing this approach and setting not only the user-agent but some other useful headers as well.

**Comment by antivanov** [comment]
Merged.
